"""init db in flask-migrate

Revision ID: 818227f1d447
Revises: 
Create Date: 2020-10-16 02:23:14.344321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818227f1d447'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest',
    sa.Column('id', sa.Integer(), server_default=sa.text("(nextval('guest_id_seq'::regclass))"), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reference',
    sa.Column('id', sa.Integer(), server_default=sa.text("(nextval('reference_id_seq'::regclass))"), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('external_link', sa.String(), nullable=True),
    sa.Column('image_link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('show',
    sa.Column('id', sa.Integer(), server_default=sa.text("(nextval('show_id_seq'::regclass))"), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('episode',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('youtube_link', sa.String(), nullable=False),
    sa.Column('official_link', sa.String(), nullable=False),
    sa.Column('image_link', sa.String(), nullable=True),
    sa.Column('published_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['show.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episode_inspired_by',
    sa.Column('episode_id', sa.String(), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], ),
    sa.ForeignKeyConstraint(['reference_id'], ['reference.id'], ),
    sa.PrimaryKeyConstraint('episode_id', 'reference_id')
    )
    op.create_table('guest_appearances',
    sa.Column('episode_id', sa.String(), nullable=True),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], )
    )
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), server_default=sa.text("(nextval('recipe_id_seq'::regclass))"), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_link', sa.String(), nullable=True),
    sa.Column('raw_ingredient_list', sa.Text(), nullable=False),
    sa.Column('raw_procedure', sa.Text(), nullable=False),
    sa.Column('episode_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe')
    op.drop_table('guest_appearances')
    op.drop_table('episode_inspired_by')
    op.drop_table('episode')
    op.drop_table('show')
    op.drop_table('reference')
    op.drop_table('guest')
    # ### end Alembic commands ###
