"""episode.published_date should be a date, not datetime

Revision ID: 960feeb4b2ef
Revises: c640bf5b87ae
Create Date: 2021-01-02 09:45:24.679912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960feeb4b2ef'
down_revision = 'c640bf5b87ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # cleanup show index missed from before
    op.drop_index('show_name_uindex', table_name='show')
    op.create_unique_constraint(None, 'show', ['name'])

    # alter "published_date" to actually be a date
    op.alter_column('episode', 'published_date', type_=sa.Date(), existing_type=sa.DateTime())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('episode', 'published_date', type_=sa.DateTime(), existing_type=sa.Date())

    op.drop_constraint('show_name_key', 'show', type_='unique')
    op.create_index('show_name_uindex', 'show', ['name'], unique=True)
    # ### end Alembic commands ###
