"""guest_appearances_pk

Revision ID: c68d372abaa7
Revises: 960feeb4b2ef
Create Date: 2021-01-04 17:08:08.023750

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'c68d372abaa7'
down_revision = '960feeb4b2ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_primary_key('guest_appearances_pk', 'guest_appearances', ['episode_id', 'guest_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('guest_appearances_pk', 'guest_appearances', type_='primary')
    # ### end Alembic commands ###
